[package]
name = "monoio-http"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
http.workspace = true
httparse.workspace = true
httpdate.workspace = true
monoio.workspace = true
